version: '1.0'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=default_db'
      - 'MYSQL_ROOT_PASSWORD=test123'
    ports:
      - '3306:3306'
#  app:
#    depends_on:
#      mysql:
#        condition: service_started
#    build: .
#    container_name: customer-management-api
#    ports:
#      - "8080:8080"