spring:
  application:
    name: customer-management-api
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/default_db
    username: root
    password: test123
    driverClassName: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: test123

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop